### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [boi1216/TnTWars#1]
ParseError: "syntax error, unexpected '}'" 
(EXCEPTION) in "plugins/TnTWars-master/src/TNTWars/game/Game" at line 232

**Comment by BogdanMakarchuk** [comment]
You 231 line:
$armor->setCustomColor(Color::get)

Not ";"

**Comment by BogdanMakarchuk** [comment]
Error: "Undefined class constant 'get'" (EX
CEPTION) in "plugins/TnTWars-master/src/TNTWars/game/Game" at line 231

**Comment by BogdanMakarchuk** [comment]
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine
\level\Level::setBlock() must be an instance of pocketmine\math\Vector3, null gi
ven, called in /root/test/plugins/TnTWars-master/src/TNTWars/ships/SmallShip.php
 on line 91" (EXCEPTION) in "src/pocketmine/level/Level" at line 1619

**Comment by boi1216** [comment]
This plugin is not finished
